package:
  name: methpype
  version: 1.0.5

source:
  url: https://files.pythonhosted.org/packages/87/ea/f14a9fb11b0e41bed6dbd007aa231cbe7721af39244a4c34e98b1e14b64e/methpype-{{ version }}.tar.gz
  sha256: 1445b6e5bcf5fc8c7cad6d1e86f88e9878a8e49c8a77de6c5d1f3193a0b35518

build:  
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - scipy
    - statsmodels
    - tqdm

test:
  imports:
    - methpype

about:
  home: https://pypi.org/project/methpype/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Python-based Illumina methylation array processing software'
  description: |
    Python-based Illumina methylation array processing software    
    Python 3.6+.
    Works primarily as a command line interface, but also supports scripting using jupyter notebooks and pandas dataframes.
  doc_url: https://life-epigenetics-methpype.readthedocs-hosted.com/en/latest/
  dev_url: http://github.com/LifeEGX/methpype
extra:
  recipe-maintainers:
    - marcmaxson
