package:
  name: methpype
  version: 1.0.1

source:
  url: https://files.pythonhosted.org/packages/00/88/eab68b60ad237ba0f9b69f862b6b92553a9646b4e5620a06e58803fa645d/methpype-1.0.1.tar.gz
  sha256: acf192a02388a2eb71fe4ae6d0bac13b174c53fb3bb98f95eaaa9e17b2394597

build:  
  noarch: python >=3.6
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - methpype

about:
  home: http://github.com/LifeEGX/methpype
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python-based Illumina methylation array preprocessing software'

  description: |
    Python-based Illumina methylation array preprocessing software    
    Python 3.6+.
    Works primarily as a command line interface, but also supports scripting using pandas dataframes.
  doc_url: https://life-epigenetics-methpype-dev.readthedocs-hosted.com/en/latest/
  dev_url: http://github.com/LifeEGX/methpype
extra:
  recipe-maintainers:
    - marcmaxson
